/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'bus' : null } |
  { 'cab' : null } |
  { 'train' : null } |
  { 'hotel' : null } |
  { 'other' : null } |
  { 'flight' : null } |
  { 'meal' : null };
export type ExpenseId = bigint;
export type Language = { 'en' : null } |
  { 'hi' : null } |
  { 'mr' : null };
export interface Receipt {
  'id' : ExpenseId,
  'imageData' : string,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : [] | [string],
  'category' : Category,
  'amount' : [] | [number],
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'preferredLanguage' : Language,
  'isPremium' : boolean,
  'userId' : UserId,
  'name' : string,
  'lastUploadDate' : Timestamp,
  'companyName' : [] | [string],
  'betaExpiryDate' : Timestamp,
  'dailyUploadCount' : bigint,
}
export interface _SERVICE {
  'addExpense' : ActorMethod<[Receipt], ExpenseId>,
  'deleteExpense' : ActorMethod<[ExpenseId], undefined>,
  'getDailyCount' : ActorMethod<[], bigint>,
  'getExpenses' : ActorMethod<[], Array<Receipt>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'updateExpense' : ActorMethod<[Receipt], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];