/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExpenseId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Category = IDL.Variant({
  'bus' : IDL.Null,
  'cab' : IDL.Null,
  'train' : IDL.Null,
  'hotel' : IDL.Null,
  'other' : IDL.Null,
  'flight' : IDL.Null,
  'meal' : IDL.Null,
});
export const Receipt = IDL.Record({
  'id' : ExpenseId,
  'imageData' : IDL.Text,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'category' : Category,
  'amount' : IDL.Opt(IDL.Float64),
});
export const PlanType = IDL.Variant({
  'annual' : IDL.Null,
  'monthly' : IDL.Null,
});
export const CreateOrderRequest = IDL.Record({ 'planType' : PlanType });
export const CreateOrderResult = IDL.Record({
  'error' : IDL.Opt(IDL.Text),
  'orderId' : IDL.Text,
  'currency' : IDL.Text,
  'success' : IDL.Bool,
  'amount' : IDL.Nat,
});
export const PremiumStatusResult = IDL.Record({
  'isPremium' : IDL.Bool,
  'premiumExpiryDate' : IDL.Opt(Timestamp),
  'planType' : IDL.Opt(PlanType),
});
export const Language = IDL.Variant({
  'en' : IDL.Null,
  'hi' : IDL.Null,
  'mr' : IDL.Null,
});
export const UserId = IDL.Principal;
export const UserProfile = IDL.Record({
  'preferredLanguage' : Language,
  'isPremium' : IDL.Bool,
  'userId' : UserId,
  'name' : IDL.Text,
  'lastUploadDate' : Timestamp,
  'companyName' : IDL.Opt(IDL.Text),
  'betaExpiryDate' : Timestamp,
  'dailyUploadCount' : IDL.Nat,
});
export const VerifyPaymentRequest = IDL.Record({
  'email' : IDL.Text,
  'razorpay_payment_id' : IDL.Text,
  'razorpay_order_id' : IDL.Text,
  'razorpay_signature' : IDL.Text,
  'planType' : PlanType,
});
export const VerifyPaymentResult = IDL.Record({
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func([Receipt], [ExpenseId], []),
  'createOrder' : IDL.Func([CreateOrderRequest], [CreateOrderResult], []),
  'deleteExpense' : IDL.Func([ExpenseId], [], []),
  'getDailyCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
  'getUserPremiumStatus' : IDL.Func(
      [IDL.Text],
      [PremiumStatusResult],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'updateExpense' : IDL.Func([Receipt], [], []),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
  'verifyPayment' : IDL.Func([VerifyPaymentRequest], [VerifyPaymentResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExpenseId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Category = IDL.Variant({
    'bus' : IDL.Null,
    'cab' : IDL.Null,
    'train' : IDL.Null,
    'hotel' : IDL.Null,
    'other' : IDL.Null,
    'flight' : IDL.Null,
    'meal' : IDL.Null,
  });
  const Receipt = IDL.Record({
    'id' : ExpenseId,
    'imageData' : IDL.Text,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'category' : Category,
    'amount' : IDL.Opt(IDL.Float64),
  });
  const PlanType = IDL.Variant({ 'annual' : IDL.Null, 'monthly' : IDL.Null });
  const CreateOrderRequest = IDL.Record({ 'planType' : PlanType });
  const CreateOrderResult = IDL.Record({
    'error' : IDL.Opt(IDL.Text),
    'orderId' : IDL.Text,
    'currency' : IDL.Text,
    'success' : IDL.Bool,
    'amount' : IDL.Nat,
  });
  const PremiumStatusResult = IDL.Record({
    'isPremium' : IDL.Bool,
    'premiumExpiryDate' : IDL.Opt(Timestamp),
    'planType' : IDL.Opt(PlanType),
  });
  const Language = IDL.Variant({
    'en' : IDL.Null,
    'hi' : IDL.Null,
    'mr' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const UserProfile = IDL.Record({
    'preferredLanguage' : Language,
    'isPremium' : IDL.Bool,
    'userId' : UserId,
    'name' : IDL.Text,
    'lastUploadDate' : Timestamp,
    'companyName' : IDL.Opt(IDL.Text),
    'betaExpiryDate' : Timestamp,
    'dailyUploadCount' : IDL.Nat,
  });
  const VerifyPaymentRequest = IDL.Record({
    'email' : IDL.Text,
    'razorpay_payment_id' : IDL.Text,
    'razorpay_order_id' : IDL.Text,
    'razorpay_signature' : IDL.Text,
    'planType' : PlanType,
  });
  const VerifyPaymentResult = IDL.Record({
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func([Receipt], [ExpenseId], []),
    'createOrder' : IDL.Func([CreateOrderRequest], [CreateOrderResult], []),
    'deleteExpense' : IDL.Func([ExpenseId], [], []),
    'getDailyCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
    'getUserPremiumStatus' : IDL.Func(
        [IDL.Text],
        [PremiumStatusResult],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'updateExpense' : IDL.Func([Receipt], [], []),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
    'verifyPayment' : IDL.Func(
        [VerifyPaymentRequest],
        [VerifyPaymentResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };