/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export interface VerifyPaymentResult {
    error?: string;
    success: boolean;
}
export type Timestamp = bigint;
export interface Receipt {
    id: ExpenseId;
    imageData: string;
    date: Timestamp;
    createdAt: Timestamp;
    notes?: string;
    category: Category;
    amount?: number;
}
export type ExpenseId = bigint;
export interface VerifyPaymentRequest {
    email: string;
    razorpay_payment_id: string;
    razorpay_order_id: string;
    razorpay_signature: string;
    planType: PlanType;
}
export interface CreateOrderRequest {
    planType: PlanType;
}
export interface PremiumStatusResult {
    isPremium: boolean;
    premiumExpiryDate?: Timestamp;
    planType?: PlanType;
}
export interface CreateOrderResult {
    error?: string;
    orderId: string;
    currency: string;
    success: boolean;
    amount: bigint;
}
export interface UserProfile {
    preferredLanguage: Language;
    isPremium: boolean;
    userId: UserId;
    name: string;
    lastUploadDate: Timestamp;
    companyName?: string;
    betaExpiryDate: Timestamp;
    dailyUploadCount: bigint;
}
export enum Category {
    bus = "bus",
    cab = "cab",
    train = "train",
    hotel = "hotel",
    other = "other",
    flight = "flight",
    meal = "meal"
}
export enum Language {
    en = "en",
    hi = "hi",
    mr = "mr"
}
export enum PlanType {
    annual = "annual",
    monthly = "monthly"
}
export interface backendInterface {
    addExpense(receipt: Receipt): Promise<ExpenseId>;
    createOrder(req: CreateOrderRequest): Promise<CreateOrderResult>;
    deleteExpense(id: ExpenseId): Promise<void>;
    getDailyCount(): Promise<bigint>;
    getExpenses(): Promise<Array<Receipt>>;
    getUserPremiumStatus(email: string): Promise<PremiumStatusResult>;
    getUserProfile(): Promise<UserProfile | null>;
    updateExpense(receipt: Receipt): Promise<void>;
    updateUserProfile(profile: UserProfile): Promise<void>;
    verifyPayment(req: VerifyPaymentRequest): Promise<VerifyPaymentResult>;
}
import type { Category as _Category, CreateOrderRequest as _CreateOrderRequest, CreateOrderResult as _CreateOrderResult, ExpenseId as _ExpenseId, Language as _Language, PlanType as _PlanType, PremiumStatusResult as _PremiumStatusResult, Receipt as _Receipt, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, VerifyPaymentRequest as _VerifyPaymentRequest, VerifyPaymentResult as _VerifyPaymentResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExpense(arg0: Receipt): Promise<ExpenseId> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(to_candid_Receipt_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(to_candid_Receipt_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOrder(arg0: CreateOrderRequest): Promise<CreateOrderResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_CreateOrderRequest_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CreateOrderResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_CreateOrderRequest_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CreateOrderResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteExpense(arg0: ExpenseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async getDailyCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyCount();
            return result;
        }
    }
    async getExpenses(): Promise<Array<Receipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPremiumStatus(arg0: string): Promise<PremiumStatusResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPremiumStatus(arg0);
                return from_candid_PremiumStatusResult_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPremiumStatus(arg0);
            return from_candid_PremiumStatusResult_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateExpense(arg0: Receipt): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(to_candid_Receipt_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(to_candid_Receipt_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfile_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfile_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyPayment(arg0: VerifyPaymentRequest): Promise<VerifyPaymentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPayment(to_candid_VerifyPaymentRequest_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_VerifyPaymentResult_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPayment(to_candid_VerifyPaymentRequest_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_VerifyPaymentResult_n35(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CreateOrderResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateOrderResult): CreateOrderResult {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PlanType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanType): PlanType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PremiumStatusResult_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PremiumStatusResult): PremiumStatusResult {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Receipt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Receipt): Receipt {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_VerifyPaymentResult_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifyPaymentResult): VerifyPaymentResult {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlanType]): PlanType | null {
    return value.length === 0 ? null : from_candid_PlanType_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: [] | [string];
    orderId: string;
    currency: string;
    success: boolean;
    amount: bigint;
}): {
    error?: string;
    orderId: string;
    currency: string;
    success: boolean;
    amount: bigint;
} {
    return {
        error: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.error)),
        orderId: value.orderId,
        currency: value.currency,
        success: value.success,
        amount: value.amount
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExpenseId;
    imageData: string;
    date: _Timestamp;
    createdAt: _Timestamp;
    notes: [] | [string];
    category: _Category;
    amount: [] | [number];
}): {
    id: ExpenseId;
    imageData: string;
    date: Timestamp;
    createdAt: Timestamp;
    notes?: string;
    category: Category;
    amount?: number;
} {
    return {
        id: value.id,
        imageData: value.imageData,
        date: value.date,
        createdAt: value.createdAt,
        notes: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.notes)),
        category: from_candid_Category_n15(_uploadFile, _downloadFile, value.category),
        amount: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.amount))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isPremium: boolean;
    premiumExpiryDate: [] | [_Timestamp];
    planType: [] | [_PlanType];
}): {
    isPremium: boolean;
    premiumExpiryDate?: Timestamp;
    planType?: PlanType;
} {
    return {
        isPremium: value.isPremium,
        premiumExpiryDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.premiumExpiryDate)),
        planType: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.planType))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredLanguage: _Language;
    isPremium: boolean;
    userId: _UserId;
    name: string;
    lastUploadDate: _Timestamp;
    companyName: [] | [string];
    betaExpiryDate: _Timestamp;
    dailyUploadCount: bigint;
}): {
    preferredLanguage: Language;
    isPremium: boolean;
    userId: UserId;
    name: string;
    lastUploadDate: Timestamp;
    companyName?: string;
    betaExpiryDate: Timestamp;
    dailyUploadCount: bigint;
} {
    return {
        preferredLanguage: from_candid_Language_n27(_uploadFile, _downloadFile, value.preferredLanguage),
        isPremium: value.isPremium,
        userId: value.userId,
        name: value.name,
        lastUploadDate: value.lastUploadDate,
        companyName: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.companyName)),
        betaExpiryDate: value.betaExpiryDate,
        dailyUploadCount: value.dailyUploadCount
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: [] | [string];
    success: boolean;
}): {
    error?: string;
    success: boolean;
} {
    return {
        error: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bus: null;
} | {
    cab: null;
} | {
    train: null;
} | {
    hotel: null;
} | {
    other: null;
} | {
    flight: null;
} | {
    meal: null;
}): Category {
    return "bus" in value ? Category.bus : "cab" in value ? Category.cab : "train" in value ? Category.train : "hotel" in value ? Category.hotel : "other" in value ? Category.other : "flight" in value ? Category.flight : "meal" in value ? Category.meal : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annual: null;
} | {
    monthly: null;
}): PlanType {
    return "annual" in value ? PlanType.annual : "monthly" in value ? PlanType.monthly : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    en: null;
} | {
    hi: null;
} | {
    mr: null;
}): Language {
    return "en" in value ? Language.en : "hi" in value ? Language.hi : "mr" in value ? Language.mr : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Receipt>): Array<Receipt> {
    return value.map((x)=>from_candid_Receipt_n13(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateOrderRequest_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderRequest): _CreateOrderRequest {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_PlanType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): _PlanType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Receipt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Receipt): _Receipt {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_VerifyPaymentRequest_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerifyPaymentRequest): _VerifyPaymentRequest {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ExpenseId;
    imageData: string;
    date: Timestamp;
    createdAt: Timestamp;
    notes?: string;
    category: Category;
    amount?: number;
}): {
    id: _ExpenseId;
    imageData: string;
    date: _Timestamp;
    createdAt: _Timestamp;
    notes: [] | [string];
    category: _Category;
    amount: [] | [number];
} {
    return {
        id: value.id,
        imageData: value.imageData,
        date: value.date,
        createdAt: value.createdAt,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        amount: value.amount ? candid_some(value.amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredLanguage: Language;
    isPremium: boolean;
    userId: UserId;
    name: string;
    lastUploadDate: Timestamp;
    companyName?: string;
    betaExpiryDate: Timestamp;
    dailyUploadCount: bigint;
}): {
    preferredLanguage: _Language;
    isPremium: boolean;
    userId: _UserId;
    name: string;
    lastUploadDate: _Timestamp;
    companyName: [] | [string];
    betaExpiryDate: _Timestamp;
    dailyUploadCount: bigint;
} {
    return {
        preferredLanguage: to_candid_Language_n31(_uploadFile, _downloadFile, value.preferredLanguage),
        isPremium: value.isPremium,
        userId: value.userId,
        name: value.name,
        lastUploadDate: value.lastUploadDate,
        companyName: value.companyName ? candid_some(value.companyName) : candid_none(),
        betaExpiryDate: value.betaExpiryDate,
        dailyUploadCount: value.dailyUploadCount
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    email: string;
    razorpay_payment_id: string;
    razorpay_order_id: string;
    razorpay_signature: string;
    planType: PlanType;
}): {
    email: string;
    razorpay_payment_id: string;
    razorpay_order_id: string;
    razorpay_signature: string;
    planType: _PlanType;
} {
    return {
        email: value.email,
        razorpay_payment_id: value.razorpay_payment_id,
        razorpay_order_id: value.razorpay_order_id,
        razorpay_signature: value.razorpay_signature,
        planType: to_candid_PlanType_n7(_uploadFile, _downloadFile, value.planType)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    planType: PlanType;
}): {
    planType: _PlanType;
} {
    return {
        planType: to_candid_PlanType_n7(_uploadFile, _downloadFile, value.planType)
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    en: null;
} | {
    hi: null;
} | {
    mr: null;
} {
    return value == Language.en ? {
        en: null
    } : value == Language.hi ? {
        hi: null
    } : value == Language.mr ? {
        mr: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    bus: null;
} | {
    cab: null;
} | {
    train: null;
} | {
    hotel: null;
} | {
    other: null;
} | {
    flight: null;
} | {
    meal: null;
} {
    return value == Category.bus ? {
        bus: null
    } : value == Category.cab ? {
        cab: null
    } : value == Category.train ? {
        train: null
    } : value == Category.hotel ? {
        hotel: null
    } : value == Category.other ? {
        other: null
    } : value == Category.flight ? {
        flight: null
    } : value == Category.meal ? {
        meal: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): {
    annual: null;
} | {
    monthly: null;
} {
    return value == PlanType.annual ? {
        annual: null
    } : value == PlanType.monthly ? {
        monthly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
